/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dump;

/**
 *
 * @author Victus
 */
public class TemplateAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Template
     */
    public TemplateAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jP_leftBar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jB_Profile = new javax.swing.JButton();
        jB_ClassAttd = new javax.swing.JButton();
        jB_Grade = new javax.swing.JButton();
        jB_studinfo = new javax.swing.JButton();
        jL_welcome = new javax.swing.JLabel();
        jL_user = new javax.swing.JLabel();
        jP_topBar = new javax.swing.JPanel();
        jL_Date = new javax.swing.JLabel();
        jL_Time = new javax.swing.JLabel();
        jB_Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Management Information System");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jP_leftBar.setBackground(new java.awt.Color(221, 59, 65));
        jP_leftBar.setPreferredSize(new java.awt.Dimension(200, 700));
        jP_leftBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Photo Icon");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 100));
        jP_leftBar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jB_Profile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB_Profile.setForeground(new java.awt.Color(255, 255, 255));
        jB_Profile.setText("Profile");
        jB_Profile.setBorder(null);
        buttonGroup1.add(jB_Profile);
        jB_Profile.setContentAreaFilled(false);
        jB_Profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_Profile.setFocusPainted(false);
        jB_Profile.setPreferredSize(new java.awt.Dimension(200, 50));
        jB_Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ProfileActionPerformed(evt);
            }
        });
        jP_leftBar.add(jB_Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, -1));

        jB_ClassAttd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB_ClassAttd.setForeground(new java.awt.Color(255, 255, 255));
        jB_ClassAttd.setText("Class Attendance");
        jB_ClassAttd.setBorder(null);
        jB_ClassAttd.setContentAreaFilled(false);
        jB_ClassAttd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_ClassAttd.setFocusPainted(false);
        jB_ClassAttd.setPreferredSize(new java.awt.Dimension(200, 50));
        jB_ClassAttd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ClassAttdActionPerformed(evt);
            }
        });
        jP_leftBar.add(jB_ClassAttd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        jB_Grade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB_Grade.setForeground(new java.awt.Color(255, 255, 255));
        jB_Grade.setText("Grade");
        jB_Grade.setBorder(null);
        jB_Grade.setContentAreaFilled(false);
        jB_Grade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_Grade.setFocusPainted(false);
        jB_Grade.setPreferredSize(new java.awt.Dimension(200, 50));
        jB_Grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_GradeActionPerformed(evt);
            }
        });
        jP_leftBar.add(jB_Grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, -1));

        jB_studinfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB_studinfo.setForeground(new java.awt.Color(255, 255, 255));
        jB_studinfo.setText("Student Info");
        jB_studinfo.setBorder(null);
        jB_studinfo.setContentAreaFilled(false);
        jB_studinfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_studinfo.setFocusPainted(false);
        jB_studinfo.setPreferredSize(new java.awt.Dimension(200, 50));
        jB_studinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_studinfoActionPerformed(evt);
            }
        });
        jP_leftBar.add(jB_studinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, -1, -1));

        jL_welcome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jL_welcome.setForeground(new java.awt.Color(255, 255, 255));
        jL_welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_welcome.setText("Welcome,");
        jP_leftBar.add(jL_welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 80, -1));

        jL_user.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jL_user.setForeground(new java.awt.Color(255, 255, 255));
        jL_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_user.setText("User");
        jP_leftBar.add(jL_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 80, -1));

        getContentPane().add(jP_leftBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jP_topBar.setBackground(new java.awt.Color(222, 225, 229));
        jP_topBar.setPreferredSize(new java.awt.Dimension(1000, 50));
        jP_topBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_Date.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jL_Date.setForeground(new java.awt.Color(51, 51, 51));
        jL_Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Date.setText("January 1, 2024 ");
        jP_topBar.add(jL_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, -1));

        jL_Time.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jL_Time.setForeground(new java.awt.Color(51, 51, 51));
        jL_Time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Time.setText("12:00:00");
        jP_topBar.add(jL_Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 120, -1));

        jB_Logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB_Logout.setForeground(new java.awt.Color(255, 51, 51));
        jB_Logout.setText("LOG OUT");
        jB_Logout.setBorderPainted(false);
        jB_Logout.setContentAreaFilled(false);
        jB_Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_Logout.setFocusPainted(false);
        jB_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_LogoutActionPerformed(evt);
            }
        });
        jP_topBar.add(jB_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, 30));

        getContentPane().add(jP_topBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_ProfileActionPerformed

    private void jB_ClassAttdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ClassAttdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_ClassAttdActionPerformed

    private void jB_GradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_GradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_GradeActionPerformed

    private void jB_studinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_studinfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_studinfoActionPerformed

    private void jB_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_LogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TemplateAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TemplateAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TemplateAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TemplateAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TemplateAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jB_ClassAttd;
    private javax.swing.JButton jB_Grade;
    private javax.swing.JButton jB_Logout;
    private javax.swing.JButton jB_Profile;
    private javax.swing.JButton jB_studinfo;
    private javax.swing.JLabel jL_Date;
    private javax.swing.JLabel jL_Time;
    private javax.swing.JLabel jL_user;
    private javax.swing.JLabel jL_welcome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jP_leftBar;
    private javax.swing.JPanel jP_topBar;
    // End of variables declaration//GEN-END:variables
}
