
package com.plm.smis.frames;

import java.net.URL;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Date;

import com.plm.smis.frames.*;
import com.plm.smis.database.Database;

public class DashboardStudent extends javax.swing.JFrame {

    private Timer timer;
    Database db = new Database();
    int userID;
    
    // NOT SELECTED
    Color p_color = Color.decode("#EFB134");
    Color txt_nonselect = Color.decode("#FFFFFF");
    
    // SELECTED
    Color btn_select = Color.decode("#E5E5E5");
    Color txt_select = Color.decode("#353535");
    
    
    public DashboardStudent(int stud_id) {
        userID = stud_id;
        initComponents();
        db.getStudUser(stud_id, jL_user);
        jP_Profile.setVisible(false);
        jP_ClassAttendance.setVisible(false);
        jP_Grade.setVisible(false);
        setIcon();
        startClock();
        setDate();
        setSize(1200, 700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jP_leftBar = new javax.swing.JPanel();
        jB_Profile = new javax.swing.JButton();
        jB_ClassAttd = new javax.swing.JButton();
        jB_Grade = new javax.swing.JButton();
        jL_welcome = new javax.swing.JLabel();
        jL_user = new javax.swing.JLabel();
        jP_topBar = new javax.swing.JPanel();
        jL_Date = new javax.swing.JLabel();
        jL_Time = new javax.swing.JLabel();
        jB_Logout = new javax.swing.JButton();
        jP_Profile = new javax.swing.JPanel();
        jL_studID_P = new javax.swing.JLabel();
        jTF_studID_P = new javax.swing.JTextField();
        jL_username_P = new javax.swing.JLabel();
        jTF_username_P = new javax.swing.JTextField();
        jL_fullN_P = new javax.swing.JLabel();
        jTF_fullN_P = new javax.swing.JTextField();
        jL_email_P = new javax.swing.JLabel();
        jTF_email_P = new javax.swing.JTextField();
        jL_contact_P = new javax.swing.JLabel();
        jTF_contact_P = new javax.swing.JTextField();
        jL_birth_P = new javax.swing.JLabel();
        jTF_birth_P = new javax.swing.JTextField();
        jL_college_P = new javax.swing.JLabel();
        jTF_college_P = new javax.swing.JTextField();
        jL_crs_P = new javax.swing.JLabel();
        jTF_crs_P = new javax.swing.JTextField();
        jL_type_P = new javax.swing.JLabel();
        jTF_type_P = new javax.swing.JTextField();
        jL_status_P = new javax.swing.JLabel();
        jTF_status_P = new javax.swing.JTextField();
        jL_yrlvl_P = new javax.swing.JLabel();
        jTF_yrlvl_P = new javax.swing.JTextField();
        jL_blk_P = new javax.swing.JLabel();
        jTF_blk_P = new javax.swing.JTextField();
        jB_enter_P = new javax.swing.JButton();
        jP_ClassAttendance = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_attendance_CA = new javax.swing.JTable();
        jP_Grade = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT_grades_G = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Management Information System");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jP_leftBar.setBackground(new java.awt.Color(239, 177, 52));
        jP_leftBar.setPreferredSize(new java.awt.Dimension(200, 700));
        jP_leftBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jB_Profile.setBackground(new java.awt.Color(239, 177, 52));
        jB_Profile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB_Profile.setForeground(new java.awt.Color(255, 255, 255));
        jB_Profile.setText("Profile");
        jB_Profile.setBorder(null);
        buttonGroup1.add(jB_Profile);
        jB_Profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_Profile.setFocusPainted(false);
        jB_Profile.setPreferredSize(new java.awt.Dimension(200, 50));
        jB_Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ProfileActionPerformed(evt);
            }
        });
        jP_leftBar.add(jB_Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, -1));

        jB_ClassAttd.setBackground(new java.awt.Color(239, 177, 52));
        jB_ClassAttd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB_ClassAttd.setForeground(new java.awt.Color(255, 255, 255));
        jB_ClassAttd.setText("Class Attendance");
        jB_ClassAttd.setBorder(null);
        jB_ClassAttd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_ClassAttd.setFocusPainted(false);
        jB_ClassAttd.setPreferredSize(new java.awt.Dimension(200, 50));
        jB_ClassAttd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ClassAttdActionPerformed(evt);
            }
        });
        jP_leftBar.add(jB_ClassAttd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        jB_Grade.setBackground(new java.awt.Color(239, 177, 52));
        jB_Grade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB_Grade.setForeground(new java.awt.Color(255, 255, 255));
        jB_Grade.setText("Grade");
        jB_Grade.setBorder(null);
        jB_Grade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_Grade.setFocusPainted(false);
        jB_Grade.setPreferredSize(new java.awt.Dimension(200, 50));
        jB_Grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_GradeActionPerformed(evt);
            }
        });
        jP_leftBar.add(jB_Grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, -1));

        jL_welcome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jL_welcome.setForeground(new java.awt.Color(255, 255, 255));
        jL_welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_welcome.setText("Welcome,");
        jP_leftBar.add(jL_welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 80, -1));

        jL_user.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jL_user.setForeground(new java.awt.Color(255, 255, 255));
        jL_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_user.setText("User");
        jP_leftBar.add(jL_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 80, -1));

        getContentPane().add(jP_leftBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jP_topBar.setBackground(new java.awt.Color(222, 225, 229));
        jP_topBar.setPreferredSize(new java.awt.Dimension(1000, 50));
        jP_topBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_Date.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jL_Date.setForeground(new java.awt.Color(51, 51, 51));
        jL_Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Date.setText("January 1, 2024 ");
        jP_topBar.add(jL_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, -1));

        jL_Time.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jL_Time.setForeground(new java.awt.Color(51, 51, 51));
        jL_Time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Time.setText("12:00:00");
        jP_topBar.add(jL_Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 120, -1));

        jB_Logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB_Logout.setForeground(new java.awt.Color(239, 177, 52));
        jB_Logout.setText("LOG OUT");
        jB_Logout.setBorderPainted(false);
        jB_Logout.setContentAreaFilled(false);
        jB_Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_Logout.setFocusPainted(false);
        jB_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_LogoutActionPerformed(evt);
            }
        });
        jP_topBar.add(jB_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, 30));

        getContentPane().add(jP_topBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        jP_Profile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_studID_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jL_studID_P.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_studID_P.setText("Student ID:");
        jP_Profile.add(jL_studID_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, 30));

        jTF_studID_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTF_studID_P.setEnabled(false);
        jTF_studID_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_studID_PActionPerformed(evt);
            }
        });
        jP_Profile.add(jTF_studID_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 220, 30));

        jL_username_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jL_username_P.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_username_P.setText("Username:");
        jP_Profile.add(jL_username_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, 30));

        jTF_username_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTF_username_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_username_PActionPerformed(evt);
            }
        });
        jP_Profile.add(jTF_username_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 220, -1));

        jL_fullN_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jL_fullN_P.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_fullN_P.setText("Full name:");
        jP_Profile.add(jL_fullN_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, 30));

        jTF_fullN_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTF_fullN_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_fullN_PActionPerformed(evt);
            }
        });
        jP_Profile.add(jTF_fullN_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 220, -1));

        jL_email_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jL_email_P.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_email_P.setText("PLM Email:");
        jP_Profile.add(jL_email_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 90, 30));

        jTF_email_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTF_email_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_email_PActionPerformed(evt);
            }
        });
        jP_Profile.add(jTF_email_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 220, 30));

        jL_contact_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jL_contact_P.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_contact_P.setText("Contact:");
        jP_Profile.add(jL_contact_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 90, 30));

        jTF_contact_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTF_contact_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_contact_PActionPerformed(evt);
            }
        });
        jP_Profile.add(jTF_contact_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 220, 30));

        jL_birth_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jL_birth_P.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_birth_P.setText("Birthdate:");
        jP_Profile.add(jL_birth_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 90, 30));

        jTF_birth_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTF_birth_P.setText("MM-DD-YYYY");
        jTF_birth_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_birth_PActionPerformed(evt);
            }
        });
        jP_Profile.add(jTF_birth_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 220, 30));

        jL_college_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jL_college_P.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_college_P.setText("College:");
        jP_Profile.add(jL_college_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 90, 30));

        jTF_college_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTF_college_P.setEnabled(false);
        jTF_college_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_college_PActionPerformed(evt);
            }
        });
        jP_Profile.add(jTF_college_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 220, 30));

        jL_crs_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jL_crs_P.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_crs_P.setText("Course:");
        jP_Profile.add(jL_crs_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 90, 30));

        jTF_crs_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTF_crs_P.setEnabled(false);
        jTF_crs_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_crs_PActionPerformed(evt);
            }
        });
        jP_Profile.add(jTF_crs_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 220, 30));

        jL_type_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jL_type_P.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_type_P.setText("Student type:");
        jP_Profile.add(jL_type_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 110, 30));

        jTF_type_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTF_type_P.setEnabled(false);
        jTF_type_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_type_PActionPerformed(evt);
            }
        });
        jP_Profile.add(jTF_type_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 220, 30));

        jL_status_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jL_status_P.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_status_P.setText("Status:");
        jP_Profile.add(jL_status_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 110, 30));

        jTF_status_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTF_status_P.setEnabled(false);
        jTF_status_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_status_PActionPerformed(evt);
            }
        });
        jP_Profile.add(jTF_status_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 220, 30));

        jL_yrlvl_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jL_yrlvl_P.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_yrlvl_P.setText("Year level:");
        jP_Profile.add(jL_yrlvl_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 110, 30));

        jTF_yrlvl_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTF_yrlvl_P.setEnabled(false);
        jTF_yrlvl_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_yrlvl_PActionPerformed(evt);
            }
        });
        jP_Profile.add(jTF_yrlvl_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 220, 30));

        jL_blk_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jL_blk_P.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_blk_P.setText("Block:");
        jP_Profile.add(jL_blk_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 110, 30));

        jTF_blk_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTF_blk_P.setEnabled(false);
        jTF_blk_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_blk_PActionPerformed(evt);
            }
        });
        jP_Profile.add(jTF_blk_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 220, 30));

        jB_enter_P.setBackground(new java.awt.Color(239, 177, 52));
        jB_enter_P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jB_enter_P.setForeground(new java.awt.Color(255, 255, 255));
        jB_enter_P.setText("Update");
        jB_enter_P.setBorderPainted(false);
        jB_enter_P.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_enter_P.setFocusPainted(false);
        jB_enter_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_enter_PActionPerformed(evt);
            }
        });
        jP_Profile.add(jB_enter_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, 110, -1));

        getContentPane().add(jP_Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 1000, 650));

        jP_ClassAttendance.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jT_attendance_CA.setBackground(new java.awt.Color(204, 204, 204));
        jT_attendance_CA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject Code", "Time", "Status"
            }
        ));
        jT_attendance_CA.setEnabled(false);
        jT_attendance_CA.setShowGrid(false);
        jScrollPane1.setViewportView(jT_attendance_CA);

        jP_ClassAttendance.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 900, 510));

        getContentPane().add(jP_ClassAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 1000, 650));

        jP_Grade.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jT_grades_G.setBackground(new java.awt.Color(204, 204, 204));
        jT_grades_G.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject Code", "Grade"
            }
        ));
        jT_grades_G.setEnabled(false);
        jT_grades_G.setShowGrid(false);
        jScrollPane2.setViewportView(jT_grades_G);

        jP_Grade.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 900, 510));

        getContentPane().add(jP_Grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 1000, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ProfileActionPerformed
        // ===== customization =====
        jB_Profile.setBackground(btn_select);
        jB_Profile.setForeground(txt_select);
        jB_ClassAttd.setBackground(p_color);
        jB_ClassAttd.setForeground(txt_nonselect);
        jB_Grade.setBackground(p_color);
        jB_Grade.setForeground(txt_nonselect);
        
        jP_Profile.setVisible(true);
        jP_ClassAttendance.setVisible(false);
        jP_Grade.setVisible(false);
        
        // ===== Display profile values =====
        jTF_studID_P.setText(String.valueOf(userID));
        jTF_username_P.setText(db.getStudProf(userID, "stud_username"));
        jTF_fullN_P.setText(db.getStudProf(userID, "stud_name"));
        jTF_email_P.setText(db.getStudProf(userID, "stud_email"));
        jTF_contact_P.setText(db.getStudProf(userID, "stud_contact"));
        jTF_birth_P.setText(db.getStudProf(userID, "stud_birth"));
        jTF_college_P.setText(db.getStudProf(userID, "stud_college"));
        jTF_crs_P.setText(db.getStudProf(userID, "stud_crs"));
        jTF_type_P.setText(db.getStudProf(userID, "stud_type"));
        jTF_status_P.setText(db.getStudProf(userID, "stud_status"));
        jTF_yrlvl_P.setText(db.getStudProf(userID, "yrlvl"));
        jTF_blk_P.setText(db.getStudProf(userID, "blk"));
    }//GEN-LAST:event_jB_ProfileActionPerformed

    private void jB_ClassAttdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ClassAttdActionPerformed
        // ===== customization =====
        jB_Profile.setBackground(p_color);
        jB_Profile.setForeground(txt_nonselect);
        jB_ClassAttd.setBackground(btn_select);
        jB_ClassAttd.setForeground(txt_select);
        jB_Grade.setBackground(p_color);
        jB_Grade.setForeground(txt_nonselect);
        
        jP_Profile.setVisible(false);
        jP_ClassAttendance.setVisible(true);
        jP_Grade.setVisible(false);   
        
        // ===== display attd datas =====
        db.getStudAttd(userID, jT_attendance_CA);
    }//GEN-LAST:event_jB_ClassAttdActionPerformed

    private void jB_GradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_GradeActionPerformed
        jB_Profile.setBackground(p_color);
        jB_Profile.setForeground(txt_nonselect);
        jB_ClassAttd.setBackground(p_color);
        jB_ClassAttd.setForeground(txt_nonselect);
        jB_Grade.setBackground(btn_select);
        jB_Grade.setForeground(txt_select);
        
        jP_Profile.setVisible(false);
        jP_ClassAttendance.setVisible(false);
        jP_Grade.setVisible(true);
        
        // ===== display attd datas =====
        db.getStudGrade(userID, jT_grades_G);
    }//GEN-LAST:event_jB_GradeActionPerformed

    private void jB_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_LogoutActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "Do you want to logout?", 
                                                   "Confirmation", JOptionPane.YES_NO_OPTION); 
          
        // Check the user's choice and display a corresponding message 
        if (choice == JOptionPane.YES_OPTION) { 
            dispose();
            LoginStudent LS = new LoginStudent();
            LS.setVisible(true);
        }
    }//GEN-LAST:event_jB_LogoutActionPerformed

    private void jTF_studID_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_studID_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_studID_PActionPerformed

    private void jTF_username_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_username_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_username_PActionPerformed

    private void jTF_fullN_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_fullN_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_fullN_PActionPerformed

    private void jTF_email_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_email_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_email_PActionPerformed

    private void jTF_contact_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_contact_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_contact_PActionPerformed

    private void jTF_birth_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_birth_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_birth_PActionPerformed

    private void jTF_college_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_college_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_college_PActionPerformed

    private void jTF_crs_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_crs_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_crs_PActionPerformed

    private void jTF_type_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_type_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_type_PActionPerformed

    private void jTF_status_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_status_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_status_PActionPerformed

    private void jTF_yrlvl_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_yrlvl_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_yrlvl_PActionPerformed

    private void jTF_blk_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_blk_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_blk_PActionPerformed

    private void jB_enter_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_enter_PActionPerformed
        if (isValidDateFormat(jTF_birth_P.getText())){
            db.updateStudProf(userID, jTF_username_P.getText(), jTF_fullN_P.getText(), jTF_email_P.getText(), jTF_contact_P.getText(), jTF_birth_P.getText());
            JOptionPane.showMessageDialog(null, "Information successfully updated.", "NOTICE" ,JOptionPane.PLAIN_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Update UNSUCCESSFUL. Please follow MM-DD-YYYY for birthdate.", "WARNING" ,JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jB_enter_PActionPerformed

    public void setIcon(){
        URL imgurl = getClass().getClassLoader().getResource("assets\\PLM_logo.png");
        ImageIcon icon = new ImageIcon(imgurl);
        setIconImage(icon.getImage()); 
    }
    
        private void setDate(){
        LocalDateTime curDate = LocalDateTime.now();
        int getYear = curDate.getYear();
        int getDay = curDate.getDayOfMonth();
        
        int getMonth = curDate.getMonthValue();
        String monthString;
        switch (getMonth){
            case 1:
                monthString = "January";
                break;
            case 2:
                monthString = "February";
                break;
            case 3:
                monthString = "March";
                break;
            case 4:
                monthString = "April";
                break;
            case 5:
                monthString = "May";
                break;
            case 6:
                monthString = "June";
                break;
            case 7:
                monthString = "July";
                break;
            case 8:
                monthString = "August";
                break;
            case 9:
                monthString = "September";
                break;
            case 10:
                monthString = "October";
                break;
            case 11:
                monthString = "November";
                break;
            case 12:
                monthString = "December";
                break;
            default:
                monthString = "null";
        }
        
        String dateToday = monthString + " " + getDay + ", " + getYear;
        jL_Date.setText(dateToday);
    }
    
    private void startClock() {
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
                String currentTime = sdf.format(new Date());
                jL_Time.setText(currentTime);
            }
        });
        timer.start();
    }
    
    public boolean isValidDateFormat(String date) {
        return date.matches("^(0[1-9]|1[0-2])-([0-2][0-9]|3[01])-[0-9]{4}$");
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardStudent(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jB_ClassAttd;
    private javax.swing.JButton jB_Grade;
    private javax.swing.JButton jB_Logout;
    private javax.swing.JButton jB_Profile;
    private javax.swing.JButton jB_enter_P;
    private javax.swing.JLabel jL_Date;
    private javax.swing.JLabel jL_Time;
    private javax.swing.JLabel jL_birth_P;
    private javax.swing.JLabel jL_blk_P;
    private javax.swing.JLabel jL_college_P;
    private javax.swing.JLabel jL_contact_P;
    private javax.swing.JLabel jL_crs_P;
    private javax.swing.JLabel jL_email_P;
    private javax.swing.JLabel jL_fullN_P;
    private javax.swing.JLabel jL_status_P;
    private javax.swing.JLabel jL_studID_P;
    private javax.swing.JLabel jL_type_P;
    private javax.swing.JLabel jL_user;
    private javax.swing.JLabel jL_username_P;
    private javax.swing.JLabel jL_welcome;
    private javax.swing.JLabel jL_yrlvl_P;
    private javax.swing.JPanel jP_ClassAttendance;
    private javax.swing.JPanel jP_Grade;
    private javax.swing.JPanel jP_Profile;
    private javax.swing.JPanel jP_leftBar;
    private javax.swing.JPanel jP_topBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTF_birth_P;
    private javax.swing.JTextField jTF_blk_P;
    private javax.swing.JTextField jTF_college_P;
    private javax.swing.JTextField jTF_contact_P;
    private javax.swing.JTextField jTF_crs_P;
    private javax.swing.JTextField jTF_email_P;
    private javax.swing.JTextField jTF_fullN_P;
    private javax.swing.JTextField jTF_status_P;
    private javax.swing.JTextField jTF_studID_P;
    private javax.swing.JTextField jTF_type_P;
    private javax.swing.JTextField jTF_username_P;
    private javax.swing.JTextField jTF_yrlvl_P;
    private javax.swing.JTable jT_attendance_CA;
    private javax.swing.JTable jT_grades_G;
    // End of variables declaration//GEN-END:variables
}
